- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yml

- name: python setup
  ansible.builtin.import_role:
    name: common
    tasks_from: python.yml

- name: system setup 
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yml
  

