- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yml
  tags:
  - deployment

- name: app setup
  # ansible.builtin.import_role:
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs.yml
  tags:
  - deployment

- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present 

- name: connect to mongodb catalogue
  ansible.builtin.command: mongosh {{ MONGODB_HOST }} --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
  register: catalogue_output

# - name: evaluate catalogue database         # get error on ths lot of time it took so siva ignore thiss
#   community.mongodb.mongodb_shell:
#     login_host: MONGODB_HOST 
#     eval: db.getMongo().getDBNames().indexOf('catalogue')
#   register: catalogue_output

# - name: print catalogue output 
#   ansible.builtin.debug:
#     msg: "{{ catalogue_output }}"

- name: look products into mongodb
  ansible.builtin.shell: mongosh --host {{ MONGODB_HOST }} </app/db/master-data.js
  when: catalogue_output.stdout | int < 0


- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yml
  tags:
  - deployment