- name: disable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable ndoejs 20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: install dependencies
  ansible.builtin.npm:
    path: /app
  tags:
  - deployment
